app/urls.py
from django.urls import path     
from . import views

app_name = 'app'
urlpatterns = [
    # Page Section:
    path('', views.index),
    path('success',views.success, name = 'success'),
    path('table',views.table, name = 'table'),
    path('form',views.form, name = 'form'),

    # Process Section
    path('reg_process', views.reg_process, name='reg_process'),   # Registration Process                                    
    path('login_process', views.login_process, name='login_process'),   # Login Process                                    
    path('success_redirect_process', views.success_redirect_process, name='success_redirect_process'),   # Login Process                                    
    path('logout_process', views.logout_process, name='logout_process'),   # Login Process                                    

]

python_examp/urls.py
from django.urls import path,include

urlpatterns = [
    path('', include('app.urls')),
    
]

app/models.py
from django.db import models
import re

# Create your models here.

class Validation(models.Manager):
    # Registration Validation
    def validate(self, data):
        error = {}

        if len(data['first_name']) < 2 :
            error['firs_name'] = "First Name should be at least 2 characters"
        
        if len(data['last_name']) < 2:
            error['last_name'] = "Last Name should be at least 2 characters"
        
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(data['email']):    # test whether a field matches the pattern            
            error['email'] = "Invalid email address!"
        
        if data['password'] != data['conf_password']:
            error['password_conf'] = "Password and Password Confirmation should Match!"
        
        if len(data['password']) < 8 :
            error['password'] = "Password Must be at least 8 characters"
        return error

class User(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    password=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    objects = Validation()

app/views.py
from django.shortcuts import render, redirect
from app.models import *
from django.contrib import messages
import bcrypt

# Page : Login Page
def index(request):
    return render(request, 'index.html')

# Process: Registration Process: Validation Included
def reg_process(request):
    # Validation Part Section
    error = User.objects.validate(request.POST)
    if len(error) > 0:
        for key, value in error.items():
            messages.error(request, value)
        return redirect('/')
    else:  # if Validation passed store the user in the db and encrypt the password
        password = request.POST['password']
        ps_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
        User.objects.create(
            first_name=request.POST['first_name'], last_name=request.POST[
                'last_name'], email=request.POST['email'], password=ps_hash
        )
        messages.success(request, "User has been created Successfully!")
        return redirect('/')
    

# Process: Login Process: Validation Included
def login_process(request):
    # see if the username provided exists in the database
    user = User.objects.filter(email=request.POST['email'])
    if user:
        logged_user = user[0]
        if bcrypt.checkpw(request.POST['password'].encode(), logged_user.password.encode()):
            # if we get True after checking the password, we may put the user id in session
            request.session['user_id'] = logged_user.id
            messages.success(request, "You have Successfully logged in")
            return redirect('/success')
        else:
            # if we didn't find anything in the database by searching by username or if the passwords don't match,
            messages.error(request, "Email or Password incorrect")
            return redirect('/')
    else:
        # if we didn't find anything in the database by searching by username or if the passwords don't match,
        messages.error(request, "Email or Password incorrect")
        return redirect('/')
    
# : This will clear the massages from messages (error / success) --> redirect to /success
def success_redirect_process(request):
    list(messages.get_messages(request))
    return redirect('/success')

# Page : Open The main page after the user successfully logged in, it will open ""
def success(request):
    # Create User Session
    user = User.objects.get(id=request.session['user_id'])
    context = {
        'user_object' : user
    }
    return render(request, 'success.html', context)


# Process : Logout
def logout_process(request):
    # This will clear the massages from messages (error / success)
    list(messages.get_messages(request))
    request.session.flush()
    return redirect('/')

# Page : table
def table(request):
    return render(request,'table.html')


# Page : form
def form(request):
    return render(request,'form.html')

app/templates/form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Test APP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Link 1</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Link 2</a>
                    </li>
                </ul>
                <form class="d-flex align-items-center">
                    <h4> Welcome , {{user_object.first_name}} {{user_object.last_name}}</h4>
                    <!-- Logout -->
                    <a href="{% url 'app:logout_process' %}" class="ms-3 btn btn-secondary">Logout</a>
                </form>
            </div>
        </div>
    </nav>

    <div class="container mt-6 pt-4" style="background-color: white;">


        <main class="pb-5">
            <div class="row justify-content-center ">
                <!-- Left Section : Table -->
                <main class="col-sm-12 text-center">
                    <form action="{% url 'app:login_process' %}" method="post">
                        {% csrf_token %}
                        <!-- Email  -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label for="" class="col-form-label">Email</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="email" name="email" class="form-control">
                            </div>
                        </div>
                        <!-- PassWord -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label for="" class="col-form-label">Password</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="password" name="password" class="form-control">
                            </div>
                        </div>
                        <!-- Description Area -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  ">
                                <h5 class="fw-bold">Description:</h5>
                                <!-- This Can be replaced with a Label from above instead of h5-->
                            </div>
                            <div class="col-sm-6">
                                <textarea name="desc" class="form-control" rows="5">Description part</textarea>
                            </div>
                        </div>
                        <!-- Dropdown list -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  "> Please Select from the menu :</div>
                            <div class="col-sm-6">
                                <select class="form-select" aria-label="Default select example">
                                    <option selected>Open this select menu</option>
                                    <option value="1">One</option>
                                    <option value="2">Two</option>
                                    <option value="3">Three</option>
                                </select>
                            </div>
                        </div>
                        <!-- Radio button -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  ">
                                <label class="form-check-label" for="flexRadioDefault1">
                                    Default radio
                                </label>
                            </div>
                            <div class="col-sm-6 d-flex">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="same_name" value="1">
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="same_name" value="2">
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="same_name" value="3">
                                </div>
                            </div>
                        </div>
                        <!-- Check Boxes -->
                        <!-- Check Box : 1 -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  ">
                                <label class="form-check-label" for="flexCheckDefault">
                                    Default checkbox
                                </label>
                            </div>
                            <div class="col-sm-6 d-flex justify-content-start">
                                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                            </div>
                        </div>
                        <!-- Check Box : 2 -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  ">
                                <label class="form-check-label" for="flexCheckDefault">
                                    Second Default checkbox
                                </label>
                            </div>
                            <div class="col-sm-6 d-flex justify-content-start">
                                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                            </div>
                            <!-- Login Button -->
                            <div class="row mb-3 justify-content-center">
                                <div class="col-sm-6 ">
                                    <button type="submit" class="btn btn-primary">Post</button>
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </div>
                                
                            </div>
                    </form>
                </main>
            </div>
        </main>
    </div>


    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <!-- The Validation Error Massages Section -->
    <div class="container mt-6 mb-3" style="background-color: white;">
        {% if messages %}
        <div class="row justify-content-center mt-3">
            <div class="col-sm-12">
                {% for massage in messages %}
                {% if massage.tags == 'error' %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Warring ! :</strong> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% if massage.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success ! :</strong> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}
        
        <div class="row"> 
            <!-- Left Section -->
            <div class="col-sm-6 ">
                <!-- Registration Section -->
                <h2 class="mt-3 mb-5">Registration</h2>
                <form action="{% url 'app:reg_process' %}" method="post">
                    {% csrf_token %}
                    <!-- First Name -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">First Name:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="text" name="first_name" class="form-control">
                        </div>
                    </div>
                    <!-- Last Name -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Last Name:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="text" name="last_name" class="form-control">
                        </div>
                    </div>
                    <!-- Email -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Email:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="email" name="email" class="form-control">
                        </div>
                    </div>
                    <!-- Password -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Password:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="password" name="password" class="form-control">
                        </div>
                    </div>
                    <!-- Confirm Password -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Confirm PW:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="password" name="conf_password" class="form-control">
                        </div>
                    </div>
                    <!-- Register Button -->
                    <div class="row mb-3 justify-content-center">
                        <div class="col-sm-6">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- Right Section -->
            <div class="col-sm-6">
                <h2 class="mt-3 mb-5">Login</h2>
                <form action="{% url 'app:login_process' %}" method="post">
                    {% csrf_token %}
                    <!-- Email  -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label for="" class="col-form-label">Email</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="email" name="email" class="form-control">
                        </div>
                    </div>
                    <!-- PassWord -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label for="" class="col-form-label">Password</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="password" name="password" class="form-control">
                        </div>
                    </div>
                    <!-- Login Button -->
                    <div class="row mb-3 justify-content-center">
                        <div class="col-sm-6">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>

    </div>
    </div>



    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>

app/templates/success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Test APP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                            href="#">Link 1</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Link 2</a>
                    </li>
                </ul>
                <form class="d-flex align-items-center">
                    <h4> Welcome , {{user_object.first_name}} {{user_object.last_name}}</h4>
                    <!-- Logout -->
                    <a href="{% url 'app:logout_process' %}" class="ms-3 btn btn-secondary">Logout</a>
                </form>
            </div>
        </div>
    </nav>

    <div class="container mt-6 pt-4" style="background-color: white;">

        <!-- The Validation Error Massages Section -->
        {% if messages %}
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Login:</strong> You Have Successfully logged in <strong> {{user_object.first_name}}
                        {{user_object.last_name}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
        {% endif %}

        <main class="pb-5">
            <div class="row justify-content-center border">
                <section class="col-sm-6 text-center">
                    This is the Left Side Of this Page
                </section>
                <section class="col-sm-6 text-center">
                    This is the Right Side Of this Page
                </section>
            </div>
        </main>
    </div>


    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>

app/templates/table.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Test APP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Link 1</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Link 2</a>
                    </li>
                </ul>
                <form class="d-flex align-items-center">
                    <h4> Welcome , {{user_object.first_name}} {{user_object.last_name}}</h4>
                    <!-- Logout -->
                    <a href="{% url 'app:logout_process' %}" class="ms-3 btn btn-secondary">Logout</a>
                </form>
            </div>
        </div>
    </nav>

    <div class="container mt-6 pt-4" style="background-color: white;">


        <main class="pb-5">
            <div class="row justify-content-center ">
                <!-- Left Section : Table -->
                <section class="col-sm-6 text-center">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">First</th>
                                <th scope="col">Last</th>
                                <th scope="col">Handle</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td>Mark</td>
                                <td>Otto</td>
                                <td>@mdo</td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>Jacob</td>
                                <td>Thornton</td>
                                <td>@fat</td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Larry the Bird</td>
                                <td>Data</td>
                                <td>@twitter</td>
                            </tr>
                        </tbody>
                    </table>
                </section>
                <!-- Right Section : Scroll Bar -->
                <section class="col-sm-6 text-center">
                    <div class="overflow-scroll" style="height: 20rem;">
                        <ul class="text-start">
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                            <li>Item</li>
                        </ul>
                    </div>

                </section>
            </div>
        </main>
    </div>


    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>